basePath: /v1
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API 支持团队
    url: http://example.com/support
  description: 这是一个使用 Gin 框架的示例 Swagger 文档。
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: 示例 API 文档
  version: "1.0"
paths:
  /user/create:
    post:
      consumes:
      - application/json
      description: 创建一个新的用户
      parameters:
      - description: Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Gender
        in: body
        name: gender
        required: true
        schema:
          type: string
      - description: Birth
        in: body
        name: birth
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: email
        schema:
          type: string
      - description: Phone
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: Avator
        in: body
        name: avator
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 创建用户
      tags:
      - 用户
  /user/getbyname:
    get:
      consumes:
      - application/json
      description: 查询用户
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 查询用户
      tags:
      - 用户
  /users:
    get:
      consumes:
      - application/json
      description: 查询所有用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 查询所有用户
      tags:
      - 用户
swagger: "2.0"
